install:
	cp ../../../out/artifacts/tests_jar/tests.jar /usr/local/bin/Freechains.jar
	cp freechains-cli.sh        /usr/local/bin/freechains
	cp freechains-host.sh       /usr/local/bin/freechains-host
	cp freechains-bootstrap.sh  /usr/local/bin/freechains-bootstrap
	ls -l /usr/local/bin/[Ff]reechains*
