install:
	cp ../../../out/artifacts/tests_main_jar/tests.main.jar /usr/local/bin/Freechains.jar
	cp freechains-host.sh /usr/local/bin/freechains-host
	cp freechains-cli.sh  /usr/local/bin/freechains
	ls -l /usr/local/bin/[Ff]reechains*