install:
	cp ../../../out/artifacts/tests_main_jar/tests.main.jar /usr/local/bin/Freechains.jar
	cp slf4j-nop-2.0.0-alpha1.jar /usr/local/bin
	cp freechains-cli.sh          /usr/local/bin/freechains
	cp freechains-host.sh         /usr/local/bin/freechains-host
	cp freechains-bootstrap.sh    /usr/local/bin/freechains-bootstrap
	ls -l /usr/local/bin/[Ff]reechains*
